name: scheduled-tasks

on:
  workflow_dispatch:

jobs:
  task:
    name: scheduled-tasks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          curl -O https://koumatsumoto.github.io/node-with-github-pages/main/bin.js
          chmod +x bin.js
          node bin.js
